wildberries_table_structure = [('Брэнд', 'STRING', ''),
                               ('Название', 'STRING', ''),
                               ('Цена', 'STRING', ''),
                               ('Скидка', 'STRING', ''),
                               ('Итого', 'STRING', ''),
                               ('[Популярность рейтинг]', 'STRING', ''),
                               ('Рейтинг', 'STRING', ''),
                               ('Кол-во отзывов', 'STRING', ''),
                               ('Тамбнейл', 'STRING', ''),
                               ('Артикул', 'STRING', ' UNIQUE NOT NULL')]

myshop_table_structure = [('Брэнд', 'STRING', ''),
                          ('Название', 'STRING', ''),
                          ('Серия', 'STRING', ''),
                          ('Цена', 'STRING', ''),
                          ('Скидка', 'STRING', ''),
                          ('Итого', 'STRING', ''),
                          ('Популярность', 'STRING', ''),
                          ('Тамбнейл', 'STRING', ''),
                          ('Артикул', 'STRING', ' UNIQUE NOT NULL'),
                          ('ISBN', 'STRING', '')]

detmir_table_structure = [('Название', 'STRING', ''),
                          ('Цена', 'STRING', ''),
                          ('Скидка', 'STRING', ''),
                          ('Итого', 'STRING', ''),
                          ('Популярность', 'STRING', ''),
                          ('Рейтинг', 'STRING', ''),
                          ('Кол-во отзывов', 'STRING', ''),
                          ('Тамбнейл', 'STRING', ''),
                          ('Код товара на сайте', 'STRING', ' UNIQUE NOT NULL'),
                          ('Артикул', 'STRING', ''),
                          ('Наличие', 'STRING', '')]
