wildberries_table_structure = [('Брэнд', 'STRING', ''),
                               ('Название', 'STRING', ''),
                               ('Цена', 'STRING', ''),
                               ('Скидка', 'STRING', ''),
                               ('Итого', 'STRING', ''),
                               ('[Популярность рейтинг]', 'STRING', ''),
                               ('Рейтинг', 'STRING', ''),
                               ('[Кол-во отзывов]', 'STRING', ''),
                               ('[Обложка товара]', 'STRING', ''),
                               ('Артикул', 'STRING', ' UNIQUE NOT NULL')]

myshop_table_structure = [('Брэнд', 'STRING', ''),
                          ('Название', 'STRING', ''),
                          ('Серия', 'STRING', ''),
                          ('Цена', 'STRING', ''),
                          ('Скидка', 'STRING', ''),
                          ('Итого', 'STRING', ''),
                          ('Популярность', 'STRING', ''),
                          ('[Обложка товара]', 'STRING', ''),
                          ('Артикул', 'STRING', ' UNIQUE NOT NULL'),
                          ('ISBN', 'STRING', '')]

detmir_table_structure = [('Название', 'STRING', ''),
                          ('Цена', 'STRING', ''),
                          ('Скидка', 'STRING', ''),
                          ('Итого', 'STRING', ''),
                          ('Популярность', 'STRING', ''),
                          ('Рейтинг', 'STRING', ''),
                          ('[Колво отзывов]', 'STRING', ''),
                          ('[Обложка товара]', 'STRING', ''),
                          ('[Код товара на сайте]', 'STRING', ' UNIQUE NOT NULL'),
                          ('Артикул', 'STRING', ''),
                          ('Наличие', 'STRING', '')]

ozon_table_structure = [('Название', 'STRING', ''),
                        ('Серия', 'STRING', ''),
                        ('Цена', 'STRING', ''),
                        ('Скидка', 'STRING', ''),
                        ('Итого', 'STRING', ''),
                        ('Популярность', 'STRING', ''),
                        ('[Тип товара]', 'STRING', ''),
                        ('Рейтинг', 'STRING', ''),
                        ('[Колво отзывов]', 'STRING', ''),
                        ('[Обложка товара]', 'STRING', ''),
                        ('[Код товара на сайте]', 'STRING', ' UNIQUE NOT NULL'),
                        ('Артикул', 'STRING', ''),
                        ('Наличие', 'STRING', '')]
